services:
  directus:
    image: directus/directus:latest
    container_name: directus_app # Choose a name for your container
    ports:
      - "8055:8055"
    environment:
      DIRECTUS_ENV: production
      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}
      DIRECTUS_SECRET: ${DIRECTUS_SECRET}
    volumes:
      - ./extensions:/directus/extensions
    restart: always
